version: 0.2
phases:
  install:
    runtime-versions:
      ruby: 2.7
    commands:
      - node --version
  build:
    commands:
      - sam build
      - sam package --template template.yml --s3-bucket $S3_BUCKET --output-template-file package.yml
artifacts:
  type: zip
  files:
    - package.yml
